### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by GhaithZamrik** [cspotcode/node-source-map-support#36]
I am not sure why or how the issue is happening exactly, but I am getting the following error when using tslog from this library on a Windows machine, although the error is not present when using a Ubuntu

`
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at retrieveSourceMapURL (C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:227:21)
    at Array.<anonymous> (C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:239:26)
    at C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:138:32
    at mapSourcePosition (C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:269:21)
    at wrapCallSite (C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:461:20)
    at prepareStackTrace (C:\Users\repo\node_modules\@cspotcode\source-map-support\source-map-support.js:541:41)
    at Function.prepareStackTrace (C:\Users\repo\node_modules\tslog\src\CallSitesHelper.ts:48:12)
    at maybeOverridePrepareStackTrace (node:internal/errors:141:29)
    at prepareStackTrace (node:internal/errors:115:5)
`

I tried different node version for this thinking that it might be the cause to why my project is failing on Windows and within WSL2 Ubuntu subsystems

Any pointers would be appreciated, been stuck on this for a whie

**Comment by cspotcode** [comment]
Is there a related issue in tslog's issue tracker?  I see some tslog code in the stack trace, too.

**Comment by cai-zhuo** [comment]
I met this problem again, but it seems to be occasional.
[It does not seem to be tslog related](https://github.com/fullstack-build/tslog/issues/139#issuecomment-1331676294)

![img_v2_7d71a026-311e-44d4-b78b-bcc8bd6efb5g](https://user-images.githubusercontent.com/44321355/206101491-01f05aa2-d634-4e83-a7a4-19ecc64b3e60.jpg)

**Comment by asnow73** [comment]
I also met this problem again
I think the reason is @babel/plugin-transform-classes in my babel.config
![image](https://github.com/cspotcode/node-source-map-support/assets/4750946/62e4d673-4790-4886-afaa-075b8b9aa283)
