### ISSUE TITLE
TypeError: Cannot read property 'Symbol(source-map-support/sharedData)' of undefined  on Windows.

### ISSUE THREAD

**Issue by nmakkarwmc** [cspotcode/node-source-map-support#47]
Execution of 1 workers started at 2023-02-27T16:35:59.019Z

[0-0] TypeError: Cannot read property 'Symbol(source-map-support/sharedData)' of undefined
[0-0]     at initializeSharedData (C:\Code\nest\nuxeo-functional-tests\node_modules\@cspotcode\source-map-support\/source-map-support.js:49:24)
[0-0]     at Object.<anonymous> (C:\Code\nest\nuxeo-functional-tests\node_modules\@cspotcode\source-map-support\/source-map-support.js:78:18)

**Comment by nmakkarwmc** [comment]
I have not seen this problem on MAC but able to see this on the Windows 10 with latest v7 of @wdio/cucumber-framework on  and I'm not sure how to fix this locally since it is a transitive dependency of @wdio/cucumber-framework. Looking forward for fix or Workaround on this .
