### ISSUE TITLE
RangeError: Maximum call stack size exceeded (problematic regexp for long in line source maps)

### ISSUE THREAD

**Issue by doctorpangloss** [cspotcode/node-source-map-support#49]
We work on a large application, and next.js transitively uses this package for inline source maps.

The regexp used to detect the contents of the source maps starts to choke on inline source maps created for Emscripten-generated loader Javascript.

```
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at retrieveSourceMapURL (C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:340:21)
    at Array.<anonymous> (C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:353:26)
    at C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:199:32
    at mapSourcePosition (C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:383:21)
    at wrapCallSite (C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:592:20)
    at Function.prepareStackTrace (C:\Users\bberman\Documents\appmana\node_modules\@cspotcode\source-map-support\source-map-support.js:671:41)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at getStackString (node:internal/util/inspect:1240:16)
    at formatError (node:internal/util/inspect:1369:15)
    at formatRaw (node:internal/util/inspect:985:14)
    at formatValue (node:internal/util/inspect:840:10)
    at inspect (node:internal/util/inspect:364:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2298:40)
```

This is actually a very painful error. I am hoping you can deal with the data URI-style values on the right hand side of the source map marker potentially without using a regular expression to find the right hand side.

**Comment by hydrosquall** [comment]
As a workaround in the build system for a Storybook build system (using webpack with babel rather than SWC), I temporarily disabled sourcemaps when working with these large files. This package is used by [babel-core](https://github.com/babel/babel/blob/5174ad182faa9cdbd7833096376abf7df3f88f25/package.json#L39) . 

These are the lines with the expensive regexp : 

https://github.com/cspotcode/node-source-map-support/blob/69baeb8ccbf9f2a342c8575f21ac81f5d711eb81/source-map-support.js#L335-L342

I noticed `postcss` faced a similar `RangeError` while looking for SourceMaps in their project . Perhaps a similar RegEx simplification could work for node source-map-support too. 

https://github.com/postcss/postcss/commit/164eb3776b8e7426fe3b26b2b59ced60d3714250

https://github.com/postcss/postcss/issues/1646
